/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-vue-typescript
// Read more: https://github.com/johnsoncodehk/vite-plugin-vue-typescript

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    // Auto-generated global component declarations
  }
} 