samples_file: "config/samples.tsv"
paths:
  raw_data_dir: "path/to/raw"
  temp_dir: "path/to/temp"
  results_dir: "path/to/results"
  logs_dir: "path/to/logs"
  benchmark_dir: "path/to/benchmark"
params:
  preprocess_method: "fastp"  # adapter_removal | fastp
  fastp_detect_adapter_for_pe: true
  adapter1: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATTCGATCTCGTATGCCGTCTTCTGCTTG"
  adapter2: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATTT"

  min_contig_len: 500
  freebayes_freq: 0.33
  freebayes_qual: 20
  bcftools_qual: 30
  bcftools_qual_low: 20
  bin_completeness: 50
  bin_contamination: 10
  pydamage_window: 35
  use_ancient_contigs: true
  pydamage_contig_column: "reference"
  pydamage_qvalue_column: "qvalue"
  pydamage_qvalue_max: 0.05
  pydamage_predicted_accuracy_column: "predicted_accuracy"
  pydamage_predicted_accuracy_min: 0.5
  min_binninglength: 1000
  maxbin2_markerset: 40
  magrefinement: true
  magrefiner: "metawrap"
  min_completeness: 50
  max_contamination: 10
  enable_checkm2: true
  enable_gunc: true
  enable_prokka: true
  enable_eggnog: true
  enable_abricate: true
  enable_rgi: false
  enable_antismash: true
  annotation_threads: 8
  abricate_db: "vfdb"
  abricate_minid: 80
  abricate_mincov: 80

databases:
  checkm_db: "/path/to/checkm1_db"
  checkm1_db: "/path/to/checkm1_db"
  checkm2_db: "/path/to/checkm2_db"
  gunc_db: "/path/to/gunc_db_or_dmnd"
  eggnog_db: "/path/to/eggnog_db"
  abricate_db: "builtin"
  rgi_db_mode: "online"
  rgi_db: ""
  antismash_db: "builtin"
  prokka_db: "builtin"

tools:
  metawrap_env: "/path/to/metawrap_env"
  pydamage_env: "/path/to/pydamage_env"
  checkm2_env: "/path/to/checkm2_env"
  gunc_env: "/path/to/gunc_env"
  prokka_env: "/path/to/prokka_env"
  eggnog_env: "/path/to/eggnog_py310_env"
  abricate_env: "/path/to/abricate_env"
  rgi_env: "/path/to/rgi_env"
  antismash_env: "/path/to/antismash_env"
