from pathlib import Path
import unittest
import xml.etree.ElementTree as ET


class WorkflowLayoutTests(unittest.TestCase):
    def test_repository_uses_workflow_entrypoint(self):
        self.assertTrue(Path("workflow/Snakefile").exists())
        self.assertFalse(Path("Snakefile").exists())
        self.assertTrue(Path(".test").exists())
        self.assertFalse(Path(".tests").exists())

    def test_workflow_entrypoint_uses_standard_config_and_rule_includes(self):
        source = Path("workflow/Snakefile").read_text(encoding="utf-8")
        self.assertIn('configfile: "config/config.yaml"', source)
        self.assertNotIn("container:", source)
        self.assertIn("pathvars:", source)
        self.assertIn('include: "rules/common.smk"', source)
        self.assertIn('include: "rules/convert.smk"', source)
        self.assertIn('include: "rules/maxquant.smk"', source)

    def test_config_defaults_live_under_config_directory(self):
        source = Path("config/config.yaml").read_text(encoding="utf-8")
        self.assertIn("sample_table: config/samples.tsv", source)
        self.assertIn("mqpar_template: workflow/templates/mqpar.template.xml", source)
        self.assertNotIn("container_image:", source)
        self.assertIn("dotnet_bin: dotnet", source)
        self.assertIn("maxquant_cmd_dll: /opt/tools/MaxQuant_v2.7.5.0/bin/MaxQuantCmd.dll", source)
        self.assertIn("thermo_raw_file_parser: ThermoRawFileParser", source)
        self.assertIn("timsconvert_bin: timsconvert", source)
        self.assertIn("openms_fileconverter: FileConverter", source)

    def test_config_sample_table_uses_test_fixtures_instead_of_root_example_inputs(self):
        source = Path("config/samples.tsv").read_text(encoding="utf-8")
        self.assertIn("sample_id\tinput_path\texperiment\tfraction", source)
        self.assertNotIn("parameter_group", source)
        self.assertIn(".test/data/example_inputs/thermo/S1_RAW.RAW", source)
        self.assertIn(".test/data/example_inputs/bruker/S2_D.d", source)
        self.assertFalse(Path("example_inputs").exists())
        self.assertTrue(Path(".test/data/example_inputs/bruker/S2_D.d/.gitkeep").exists())

    def test_config_readme_documents_config_and_sample_table(self):
        source = Path("config/README.md").read_text(encoding="utf-8")
        self.assertIn("config.yaml", source)
        self.assertIn("config/config.local.yaml", source)
        self.assertIn("samples.tsv", source)
        self.assertIn("sample_id", source)
        self.assertIn("input_path", source)
        self.assertIn("experiment", source)
        self.assertIn("fraction", source)
        self.assertNotIn("parameter_group", source)
        self.assertIn("workflow/templates/mqpar.template.xml", source)
        self.assertIn("results/maxquant/mqpar/all_samples.mqpar.xml", source)
        self.assertIn("mqpar", source)
        self.assertNotIn("container_image", source)
        self.assertIn("snakemake", source)
        self.assertIn("entrypoint.sh", source)
        self.assertIn("/opt/tools/MaxQuant_v2.7.5.0/bin/MaxQuantCmd.dll", source)
        self.assertIn("/data", source)
        self.assertIn("/workspace/results", source)
        self.assertIn("/data/project/S1_F1.RAW", source)
        self.assertIn("/data/project/S2.d", source)

    def test_template_moves_under_workflow_directory(self):
        template = Path("workflow/templates/mqpar.template.xml")
        text = template.read_text(encoding="utf-8")
        root = ET.parse(template).getroot()

        self.assertFalse(Path("templates/mqpar.template.xml").exists())
        self.assertNotIn("/data/sun_hengxi_2024/lwt/paleoproteomics", text)
        self.assertNotIn("20141110_QEp1_LC7_PhGe_4_53_W1_1.mzML", text)
        self.assertEqual(root.findtext(".//fastaFiles/FastaFileInfo/fastaFilePath"), "/path/to/reference.fasta")
        self.assertEqual(root.findtext(".//filePaths/string"), "/path/to/input.mzML")
        self.assertIsNotNone(root.find(".//parameterGroups"))
        self.assertIsNotNone(root.find(".//maxQuantVersion"))
        self.assertIsNotNone(root.find(".//lfqTopNPeptides"))
        self.assertIsNotNone(root.find(".//msmsParamsArray"))
        self.assertIsNotNone(root.find(".//matchBetweenRuns"))
        self.assertIsNotNone(root.find(".//peptideFdr"))

    def test_readme_documents_new_layout(self):
        source = Path("README.md").read_text(encoding="utf-8")
        self.assertIn("workflow/Snakefile", source)
        self.assertIn("config/config.yaml", source)
        self.assertIn("config/config.local.yaml", source)
        self.assertIn("config/samples.tsv", source)
        self.assertIn("workflow/templates/mqpar.template.xml", source)
        self.assertIn("docker/Dockerfile", source)
        self.assertIn("docker/environment.yml", source)
        self.assertIn("docker/entrypoint.sh", source)
        self.assertIn("hub.docker.com/repository/docker/xreal1ty/appam-paleoproteomics", source)
        self.assertIn("xreal1ty/appam-paleoproteomics:latest", source)
        self.assertIn("xreal1ty/appam-paleoproteomics:v0.1.3", source)
        self.assertIn("docker pull xreal1ty/appam-paleoproteomics:latest", source)
        self.assertIn("build context", source)
        self.assertIn("root of the Docker packaging directory", source)
        self.assertIn(".test/data/example_inputs", source)
        self.assertIn(".test/unit", source)
        self.assertIn(".test/integration", source)
        self.assertIn("docker run", source)
        self.assertIn("snakemake --cores", source)
        self.assertIn("snakemake --configfile config/config.local.yaml --cores 4", source)
        self.assertIn("entrypoint.sh", source)
        self.assertIn("/opt/tools/MaxQuant_v2.7.5.0/bin/MaxQuantCmd.dll", source)
        self.assertIn("-v \"$PWD\":/workspace", source)
        self.assertIn("-v /path/to/raw_data:/data", source)
        self.assertIn("/workspace/results", source)
        self.assertIn("runtime dependencies", source)
        self.assertIn("mounted at runtime", source)
        self.assertIn("without rebuilding the container", source)
        self.assertIn("Run Without Docker", source)
        self.assertIn("ThermoRawFileParser", source)
        self.assertIn("timsconvert", source)
        self.assertIn("OpenMS", source)
        self.assertIn("MaxQuant", source)
        self.assertIn("dotnet", source)
        self.assertIn("conda", source)
        self.assertNotIn("docs/plans/file_converter.sh", source)
        self.assertNotIn("docs/plans/mqpar.xml", source)

    def test_reference_inputs_move_out_of_repository_root(self):
        self.assertFalse(Path("file_converter.sh").exists())
        self.assertFalse(Path("mqpar.xml").exists())

    def test_docker_assets_live_in_repository_root_docker_directory(self):
        self.assertTrue(Path("docker/Dockerfile").exists())
        self.assertTrue(Path("docker/entrypoint.sh").exists())
        self.assertTrue(Path("docker/environment.yml").exists())
        self.assertTrue(Path("docker/requirements-pypi.txt").exists())

    def test_docker_runtime_assets_use_relocated_openms_layout(self):
        dockerfile = Path("docker/Dockerfile").read_text(encoding="utf-8")
        entrypoint = Path("docker/entrypoint.sh").read_text(encoding="utf-8")

        self.assertIn("patchelf", dockerfile)
        self.assertIn("COPY environment.yml /opt/environment.yml", dockerfile)
        self.assertIn("COPY requirements-pypi.txt /opt/requirements-pypi.txt", dockerfile)
        self.assertIn("COPY vendor/wheels /opt/vendor/wheels", dockerfile)
        self.assertIn("COPY entrypoint.sh /entrypoint.sh", dockerfile)
        self.assertNotIn("COPY docker/environment.yml /opt/environment.yml", dockerfile)
        self.assertNotIn("COPY docker/requirements-pypi.txt /opt/requirements-pypi.txt", dockerfile)
        self.assertNotIn("COPY docker/entrypoint.sh /entrypoint.sh", dockerfile)
        self.assertIn("install_local_or_remote()", dockerfile)
        self.assertIn('install_local_or_remote "pyimzML"', dockerfile)
        self.assertIn('install_local_or_remote "pyTDFSDK"', dockerfile)
        self.assertIn('install_local_or_remote "pyBaf2Sql"', dockerfile)
        self.assertIn('install_local_or_remote "timsconvert"', dockerfile)
        self.assertIn("/opt/vendor/wheels", dockerfile)
        self.assertIn("git+https://github.com/gtluu/pyimzML.git", dockerfile)
        self.assertIn("git+https://github.com/gtluu/pyTDFSDK.git", dockerfile)
        self.assertIn("git+https://github.com/gtluu/pyBaf2Sql.git", dockerfile)
        self.assertIn("git+https://github.com/gtluu/timsconvert.git", dockerfile)
        self.assertIn("COPY tools/openms-development/bin /opt/tools/openms-development/bin", dockerfile)
        self.assertIn("COPY tools/openms-development/lib /opt/tools/openms-development/lib", dockerfile)
        self.assertIn("COPY tools/openms-development/OpenMS/share /opt/tools/openms-development/share", dockerfile)
        self.assertNotIn("COPY tools/openms-development /opt/tools/openms-development", dockerfile)
        self.assertIn(
            "patchelf --set-rpath /opt/conda/envs/paleoproteomics/lib:/opt/tools/openms-development/lib",
            dockerfile,
        )
        self.assertIn("/opt/conda/envs/paleoproteomics/lib/python3.11/site-packages/PySide6/Qt/lib", dockerfile)
        self.assertIn(
            "mv /opt/conda/envs/paleoproteomics/bin/timsconvert /opt/conda/envs/paleoproteomics/bin/timsconvert.real",
            dockerfile,
        )
        self.assertIn(
            'export LD_LIBRARY_PATH=${PYSIDE6_QT_LIB}:/opt/conda/envs/paleoproteomics/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}',
            dockerfile,
        )
        self.assertIn('exec /opt/conda/envs/paleoproteomics/bin/timsconvert.real "$@"', dockerfile)
        self.assertNotIn("ENV PATH=/opt/tools/bin:/opt/conda/envs/paleoproteomics/bin", dockerfile)
        self.assertNotIn("ENV LD_LIBRARY_PATH=/opt/conda/envs/paleoproteomics/lib", dockerfile)
        self.assertNotIn("LD_LIBRARY_PATH=/opt/conda/envs/paleoproteomics/lib", entrypoint)
        self.assertIn("LD_LIBRARY_PATH=/opt/tools/openms-development/lib", entrypoint)
        self.assertNotIn("export PATH=/opt/tools/bin:$PATH", entrypoint)
        self.assertIn("pyTDFSDK/tims.py", dockerfile)
        self.assertIn("extract_2d_tdf_spectrum", dockerfile)
        self.assertIn("if scan_begin != 0:", dockerfile)
        self.assertIn("scan_end = scan_end - scan_begin", dockerfile)
        self.assertIn("scan_begin = 0", dockerfile)

    def test_docker_environment_includes_qt_runtime_libraries(self):
        environment = Path("docker/environment.yml").read_text(encoding="utf-8")

        self.assertIn("  - libegl", environment)
        self.assertIn("  - libgl", environment)
        self.assertIn("  - libglvnd", environment)
        self.assertIn("  - libglx", environment)
        self.assertIn("  - libxkbcommon", environment)
        self.assertIn("  - libxcb", environment)
        self.assertIn("  - wayland", environment)
        self.assertIn("  - xcb-util", environment)
        self.assertIn("  - xcb-util-cursor", environment)
        self.assertIn("  - xcb-util-image", environment)
        self.assertIn("  - xcb-util-keysyms", environment)
        self.assertIn("  - xcb-util-renderutil", environment)
        self.assertIn("  - xcb-util-wm", environment)

    def test_gitignore_covers_snakemake_runtime_directories(self):
        source = Path(".gitignore").read_text(encoding="utf-8")
        self.assertIn(".snakemake/", source)
        self.assertIn(".snakemake-cache/", source)
        self.assertIn(".snakemake-home/", source)
        self.assertIn(".snakemake-tmp/", source)
        self.assertNotIn(".test/", source)
        self.assertNotIn(".tests/", source)

    def test_ci_workflow_exists_and_runs_core_checks(self):
        source = Path(".github/workflows/ci.yml").read_text(encoding="utf-8")
        self.assertIn("actions/checkout@", source)
        self.assertIn("actions/setup-python@", source)
        self.assertNotIn("cache: pip", source)
        self.assertNotIn('cache: "pip"', source)
        self.assertIn("snakemake --lint", source)
        self.assertIn("python3 -m unittest discover -s .test/unit", source)
        self.assertIn("python3 -m unittest discover -s .test/integration", source)
        self.assertIn("snakemake -n --cores 1", source)

    def test_rule_files_use_template_style_layout(self):
        snakefile = Path("workflow/Snakefile").read_text(encoding="utf-8")
        convert_rules = Path("workflow/rules/convert.smk").read_text(encoding="utf-8")
        maxquant_rules = Path("workflow/rules/maxquant.smk").read_text(encoding="utf-8")
        common_rules = Path("workflow/rules/common.smk").read_text(encoding="utf-8")
        render_script = Path("workflow/scripts/render_mqpar_rule.py").read_text(encoding="utf-8")

        self.assertNotIn("from pathlib import Path", snakefile)
        self.assertNotIn('container: config.get("container_image"', snakefile)
        self.assertIn('expand("<results>/mzml/{sample}.mzML", sample=SAMPLE_IDS)', snakefile)
        self.assertIn('"<maxquant>/mqpar/all_samples.mqpar.xml"', snakefile)
        self.assertIn('"<maxquant>/combined/txt/proteinGroups.txt"', snakefile)
        self.assertNotIn("MZML_TARGETS,", snakefile)
        self.assertNotIn("str(MQPAR_OUTPUT)", snakefile)
        self.assertNotIn("str(PROTEIN_GROUPS)", snakefile)
        self.assertNotIn("RAW_MZML =", common_rules)
        self.assertNotIn("BRUKER_MZML =", common_rules)
        self.assertNotIn("FINAL_MZML =", common_rules)
        self.assertNotIn("MQPAR_OUTPUT =", common_rules)
        self.assertNotIn("PROTEIN_GROUPS =", common_rules)
        self.assertIn("rule thermo_raw_to_mzml", convert_rules)
        self.assertIn("rule bruker_d_to_mzml", convert_rules)
        self.assertIn("rule finalize_raw_mzml", convert_rules)
        self.assertIn("rule finalize_bruker_mzml", convert_rules)
        self.assertNotIn("if [ ! -f", convert_rules)
        self.assertNotIn("mkdir -p", convert_rules)
        self.assertNotIn("conda:", convert_rules)
        self.assertNotIn("container:", convert_rules)
        self.assertIn('mzml="<results>/thermo/{sample}.mzML"', convert_rules)
        self.assertIn('mzml="<results>/bruker/{sample}.mzML"', convert_rules)
        self.assertIn("outdir=lambda wildcards, output: output.mzml[:-5]", convert_rules)
        self.assertNotIn('mzml="<results>/mzml/raw/{sample}/{sample}.mzML"', convert_rules)
        self.assertNotIn('mzml=directory("<results>/mzml/bruker/{sample}")', convert_rules)
        self.assertNotIn('mzml=directory("<results>/bruker/{sample}")', convert_rules)
        self.assertIn('-b={output.mzml:q}', convert_rules)
        self.assertIn('{input.mzml:q}', convert_rules)
        self.assertIn("{input.raw:q}", convert_rules)
        self.assertIn("{output.mzml:q}", convert_rules)
        self.assertIn("mv {params.outdir:q}/*.mzML {output.mzml:q}", convert_rules)
        self.assertNotIn("if [ ! -f", maxquant_rules)
        self.assertNotIn("conda:", maxquant_rules)
        self.assertNotIn("container:", maxquant_rules)
        self.assertIn("script:", maxquant_rules)
        self.assertIn('"../scripts/render_mqpar_rule.py"', maxquant_rules)
        self.assertNotIn("run:", maxquant_rules)
        self.assertIn("> {log:q} 2>&1", maxquant_rules)
        self.assertNotIn("> ./{log:q} 2>&1", maxquant_rules)
        self.assertNotIn("from __future__ import annotations", render_script)
        self.assertNotIn("snakemake.configfiles", render_script)
        self.assertIn("config_data=snakemake.config", render_script)
        self.assertNotIn("snakemake.params.mzml_dir", render_script)
        self.assertIn("MZML_INPUTS = [Path(path) for path in snakemake.input.mzmls]", render_script)
        self.assertIn("MZML_DIR = MZML_INPUTS[0].parent", render_script)
        self.assertIn("SAMPLE_IDS", common_rules)
        self.assertIn("_raw_input", common_rules)
        self.assertIn("_d_input", common_rules)


if __name__ == "__main__":
    unittest.main()
